# Generated by Django 6.0.6 on 2026-06-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_knowledgearticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgearticle',
            name='category',
        ),
    ]
