# Generated by Django 6.0.6 on 2026-06-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_remove_knowledgearticle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
